export const IDEA_PROPOSAL_QUESTIONS = [
  { key: "problem", label: "1. What specific SM challenges are you facing right now?" },
  { key: "whoExperiences", label: "2. Who in your life is affected by Selective Mutism?" },
  { key: "problemImportance", label: "3. Why is addressing this now important to you?" },
  { key: "currentSolutions", label: "4. What have you already tried to address your SM?" },
  { key: "ideaName", label: "5. What name would you like to use on the platform?" },
  { key: "ideaDescription", label: "6. Briefly describe your SM journey so far in your own words." },
  { key: "valueProposition", label: "7. What would meaningful progress with SM look like for you?" },
  { key: "idealCustomer", label: "8. How do you identify — person with SM, parent, caregiver, adult, or professional?" },
  { key: "targetMarket", label: "9. What settings are most affected by SM? (school, work, social, family)" },
  { key: "marketSize", label: "10. How long have you or your loved one been experiencing SM?" },
  { key: "customerReach", label: "11. Who is currently in your support network?" },
  { key: "hasCustomers", label: "12. Are you currently working with any therapist or SM specialist?" },
  { key: "customerCount", label: "13. How often do you access professional support currently?" },
  { key: "hasRevenue", label: "14. Have you had any breakthroughs or progress moments with SM?" },
  { key: "revenueAmount", label: "15. Describe a specific moment of progress, however small." },
  { key: "revenueRecurring", label: "16. Is progress consistent, or does it come and go?" },
  { key: "productUsage", label: "17. Do you currently have any daily strategies that help?" },
  { key: "monetization", label: "18. What type of support would help most? (1-on-1, group, resources)" },
  { key: "pricing", label: "19. How much time per week can you dedicate to your SM journey?" },
  { key: "mainCosts", label: "20. What are your biggest emotional or practical barriers right now?" },
  { key: "successIn12Months", label: "21. What does success look like for you in 12 months?" },
  { key: "directCompetitors", label: "22. What resources or programs have you researched or tried?" },
  { key: "competitorStrengths", label: "23. What has worked well in those approaches?" },
  { key: "competitorWeakness", label: "24. What was missing or didn't fit your needs?" },
  { key: "currentStage", label: "25. How would you describe your current stage? (just starting, some progress, seeking specialist help)" },
  { key: "hasDemo", label: "26. Do you have a specific goal or milestone in mind right now?" },
  { key: "existingFeatures", label: "27. What coping strategies or tools are already helping you?" },
  { key: "featuresToBuild", label: "28. What skills or strategies do you still want to develop?" },
  { key: "foundedBefore", label: "29. Have you sought SM support or treatment before?" },
  { key: "soloOrCoFounders", label: "30. Are you navigating this alone or with family/caregivers involved?" },
  { key: "personalSkills", label: "31. What personal strengths do you bring to your SM journey?" },
  { key: "missingSkills", label: "32. What do you feel is still missing in your understanding of SM?" },
  { key: "timePerWeek", label: "33. How much time per week can you commit to your support journey?" },
  { key: "personalInvestment", label: "34. Have you invested in any SM-specific programs or resources?" },
  { key: "externalFunding", label: "35. Are there family members or caregivers actively supporting your journey?" },
  { key: "fundingNeeded", label: "36. What level of engagement are you looking for? (light touch, regular check-ins, intensive)" },
  { key: "fundingUseCase", label: "37. What would your ideal support experience look like?" },
  { key: "investorType", label: "38. What type of guide are you looking for? (lived experience, clinical, parent of SM child, adult with SM)" },
  { key: "nextSteps", label: "39. What are the next 3 steps you want to take on your SM journey?" },
  { key: "currentObstacle", label: "40. What is your biggest current obstacle to progress?" },
  { key: "mentorHelp", label: "41. What help do you need most from your SM Guide?" },
  { key: "technicalExpertHelp", label: "42. What help do you need from SM Specialists? (speech therapy, CBT, anxiety, school support)" }
] as const;
